sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: quviTRiejf5m2P+bMyfwV5v0r55Fl2bTyRsqcDCNOGIx9OkkUaYAbUWedqG5zOUOz8jd4cR1YONjzYTz10d+4KkHCvo2VhZb4VddydJXTmfjC9Wm3n+mIfrgV3EXoTqr9EXuW+U1X8DYaPJ15sukFOL5mlPf6sSFQNnd445bs0L+WORMf5Z99Goll2IjhYsMT84hzOLQa5bqlrr2NemkxUhhdxOYkm+HYWC8aqXA/TpmV9nRIBsmTDcLU6k7O2LX0Tgxewke9/wNzIX/JkUlcJRZxWLUjPxwdI3QxzWqjJFcjuQ++9dBrK4Zak61q2U0l0zJWsasiYLLYzQmToC/Zub0ucJRkxl4ncNOEaEBK9LLfnPY4zO1IWOolejC9kHAiWECx8oMrmyfMV0q7UdVmvFgwPkaNm34laAySiziNXS6ldL1C2nJU3oIvpdgh3PfJTezk493nR8t0TJFc8WTgz+k3aVBFIhy9Eqq/WCvnEPIc3XuxCocWVgpIy2lB1W3yGUmbqgKPKU98TKvu1nqAyCu7ekiuWFeagV+Gb0jvU89i1CY6DqzVp7QLZehn6G8ZTdez1Di1pJyHNQp/8qmunf1rmoIsf56Vnfteenm4F8UDglEKaF4j1PU0/s8cepUv88X/CjrnXZ87inkD85K9Jka/Kusalmr35okFDDzw5w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Chess-History-and-Reminiscences_4902
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy